PR5
8and-rew8/qa-automation-java pull request #5
Opened 2021-08-17 23:40 UTC by 8and-rew8

refactor all already existed methods to non-static; create classes for Loan Request and Loan Response with enum parameters

2021-08-18 12:25 UTC, pshakhov requested changes

2021-08-18 12:25 UTC, pshakhov commented on app/src/main/java/com/tinkoff/edu/test/LoanCalcTest.java
> +                        new LoanRequest(ClientType.PERSON,10,1000))
лучше писать как принято) пробел после знаков препинания
```suggestion
                        new LoanRequest(ClientType.PERSON, 10, 1000))
```

2021-08-18 12:25 UTC, pshakhov commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcDao.java
> +        return new LoanResponse();
так ведь нужно, при вызове save создавать объект? возможно я что-то упустил

2021-08-18 17:20 UTC, 8and-rew8 commented on app/src/main/java/com/tinkoff/edu/test/LoanCalcTest.java
> +                        new LoanRequest(ClientType.PERSON,10,1000))
в идее там подставлены подсказки и не видно, что пробелов нет))

2021-08-18 17:22 UTC, 8and-rew8 commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcDao.java
> +        return new LoanResponse();
так мы вызываем save и создается объект класса LoanResponse
в лекции на этот счет вроде нет пояснений)

2021-08-19 06:31 UTC, pshakhov approved these changes

2021-08-19 06:35 UTC, merged