PR
8and-rew8/qa-automation-java pull request #8
Opened 2021-08-29 23:50 UTC by 8and-rew8

Add logic for approve and deny requests, add new tests, reach up to 90% coverage

2021-08-30 10:14 UTC, pshakhov requested changes
в целом все хорошо, задание выполнено, но необходимо внести небольшие правки

2021-08-30 10:14 UTC, pshakhov commented on app/pom.xml
> +        <executions>
подключение именно с такими параметрами из примера какого-то? а если с дефолтными настройками оставить?

2021-08-30 10:14 UTC, pshakhov commented on app/src/main/java/com/tinkoff/edu/app/DefaultLoanCalcService.java
> +        if (((loanRequest.getType() == ClientType.PERSON) & (loanRequest.getAmount() <= 10_000.0) &
очень тяжелая конструкция, если нужно будет добавить еще условий или же изменить значения в них, офигеешь

я бы извлек несколько функций, в одной проверка дат, в других фин. в зависимости от типа клиента, например

2021-08-30 10:14 UTC, pshakhov commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +        } else if (loanRequest.getAmount() < 0) {
if в теле теста плохой признак - это может быть как и признак необходимости извлечения метода, и, скорее всего, что тест можно и нужно разбить на несколько

2021-08-30 10:14 UTC, pshakhov commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +        } else if (loanRequest.getMonths() < 0) {
аналогично

2021-08-30 10:14 UTC, pshakhov commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +        } else if (loanRequest.getType() == ClientType.OOO) {
+1

2021-08-30 10:14 UTC, pshakhov commented on app/src/test/java/com/tinkoff/edu/AppTest.java
>      public void Init() {
этот блок все еще нужен и поля из него используются где-то? если нет, то лучше убрать

2021-08-30 10:33 UTC, 8and-rew8 commented on app/pom.xml
> +        <executions>
это он скинул в слак прям кусок, я просто вставил
дефолтные настройки это какие?

2021-08-30 10:47 UTC, pshakhov commented on app/pom.xml
> +        <executions>
```suggestion
                <executions>
                    <execution>
                        <id>report</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>report-aggregate</goal>
                        </goals>
                    </execution>
                </executions>

```

2021-08-30 10:48 UTC, pshakhov commented on app/pom.xml
> +        <executions>
или так
```suggestion
```xml
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                </executions>
```
```
нужно почитать видимо, что для чего используется

2021-08-30 13:51 UTC, pshakhov commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +        } else if (loanRequest.getMonths() < 0) {
@8and-rew8 , кстати говоря, в случае некорректных аргументов вообще стоило бы бросить исключение (зачем твоему сервису просчитывать нереальные кейсы - проще сразу отбить запрос на его валидации)

2021-08-30 13:52 UTC, 8and-rew8 commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +        } else if (loanRequest.getMonths() < 0) {
исключения он еще не рассказывал, но я написал отдельный метод для отсеивания таких кейсов, щас как раз подбиваю код

2021-08-30 21:54 UTC, 8and-rew8 commented on app/src/main/java/com/tinkoff/edu/app/DefaultLoanCalcService.java
> +        if (((loanRequest.getType() == ClientType.PERSON) & (loanRequest.getAmount() <= 10_000.0) &
перепилю

2021-08-30 21:54 UTC, 8and-rew8 commented on app/src/test/java/com/tinkoff/edu/AppTest.java
>      public void Init() {
блок нужен, там репозиторий и сервис создается для всех тестов

2021-08-31 07:28 UTC, pshakhov commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +    @DisplayName("Нельзя дать кредит на 0 месяцнв")
```suggestion
    @DisplayName("Нельзя дать кредит на 0 месяцев")
```

2021-08-31 07:33 UTC, pshakhov commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +        LoanRequest loanRequestForIp = new LoanRequest(ClientType.IP, 10, 1000);
благодаря проверке реквеста тело тестов усложнилось, теперь они сложнее читаются + выглядят так, что вместо одной проверки их две. быть может валидацию реквеста можно занести под капот с расчетом решения?

2021-09-01 08:24 UTC, pshakhov commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +        int responseId = loanResponse.getRequestId();
везде где responseId - можно обойтись без создания доп переменной - loanResponse.responseId

2021-09-01 08:26 UTC, pshakhov commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +        assertEquals(1, responseId,
здесь проиграл с сообщением)

2021-09-01 08:29 UTC, 8and-rew8 commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +        int responseId = loanResponse.getRequestId();
а так придется везде пихать loanResponse.getRequestId();
чем это лучше?

2021-09-01 08:30 UTC, pshakhov commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +        int responseId = loanResponse.getRequestId();
тогда будет 1 строка) - с ассертом

2021-09-01 08:30 UTC, pshakhov requested changes
все хорошо, но хотелось бы увидеть еще совсем минорные правки

2021-09-01 08:33 UTC, 8and-rew8 commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +        int responseId = loanResponse.getRequestId();
типа что будет в тесте всего 3 строчки? это же никак не влияет на работу

2021-09-01 08:33 UTC, 8and-rew8 commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +        assertEquals(1, responseId,
поправил

2021-09-01 08:37 UTC, 8and-rew8 commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +        int responseId = loanResponse.getRequestId();
только на внешний вид, а читается код с отдельной переменной проще

2021-09-01 08:45 UTC, 8and-rew8 commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +    @DisplayName("Нельзя дать кредит на 0 месяцнв")
поправил

2021-09-01 08:45 UTC, 8and-rew8 commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +        LoanRequest loanRequestForIp = new LoanRequest(ClientType.IP, 10, 1000);
сделал

2021-09-01 11:44 UTC, pshakhov approved these changes

2021-09-01 11:47 UTC, merged